apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- name: ghcr.io/KubeHatesMe/edu12-frontend
  newTag: "20230326152802"
- name: ghcr.io/kubehatesme/edu12-frontend
  newTag: "20230327080417"
